name: My PHP Workflow

on: [push]

jobs:
  run-php-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PHP script
      run: php script.php
      env:
        PASSWORD: ${{ secrets.TEST_PASS }}